package com.example.vcloset.logic.entity.clothing.clothingType;

public enum ClothingTypeEnum {

    CAMISETA_MANGA_CORTA(SubType.CAMISETA),
    CAMISETA_MANGA_LARGA(SubType.CAMISETA),
    CAMISETA_SIN_MANGAS(SubType.CAMISETA),


    CAMISA_CASUAL(SubType.CAMISA),
    CAMISA_FORMAL(SubType.CAMISA),
    CAMISA_CON_BOTONES_ABAJO(SubType.CAMISA),
    CAMISA_POLO(SubType.CAMISA),

    BLUSA_CASUAL(SubType.BLUSA),
    BLUSA_ELEGANTE(SubType.BLUSA),
    BLUSA_DE_MANGA_CORTA(SubType.BLUSA),
    BLUSA_MANGA_LARGA(SubType.BLUSA),

    SUDADERA_CON_CAPUCHA(SubType.SUDADERA),
    SUDADERA_SIN_CAPUCHA(SubType.SUDADERA),
    SUDADERA_CON_CREMALLERA(SubType.SUDADERA),

    TOP_CROP(SubType.TOP),
    TOP_BRALETTE(SubType.TOP),
    TOP_TANK(SubType.TOP),

    OTROS_TOPS(SubType.OTROS_SUPERIORES),

    ////////////////////
    //PANTS
    PANTALONES_DE_MEZCLILLA(SubType.PANTALONES),
    PANTALONES_DE_TRAJE(SubType.PANTALONES),
    PANTALONES_SWEETPANTS(SubType.PANTALONES),
    PANTALONES_CARGO(SubType.PANTALONES),

    FALDA(SubType.FALDA),
    FALDA_LARGA(SubType.FALDA),
    FALDA_MEDIA(SubType.FALDA),
    FALDA_MINI(SubType.FALDA),
    FALDA_PLISADA(SubType.FALDA),

    LEGGINGS_ATLETICOS(SubType.LEGGINGS),
    LEGGINGS_CASUAL(SubType.LEGGINGS),
    LEGGINGS_DE_CUERO_SINTÉTICO(SubType.LEGGINGS),

    PANTALONES_CORTOS_CASUALES(SubType.PANTALONES_CORTOS),
    PANTALONES_CORTOS_ATLETICOS(SubType.PANTALONES_CORTOS),
    PANTALONES_CORTOS_DE_MEZCLILLA(SubType.PANTALONES_CORTOS),
    SHORTS_BERMUDA(SubType.PANTALONES_CORTOS),

    BAÑADOR_ATLETICO_PANTALONES_CORTOS(SubType.BAÑADOR_INFERIOR),
    BAÑADOR_CASUAL_PANTALONES_CORTOS(SubType.BAÑADOR_INFERIOR),

    OTROS(SubType.OTROS_INFERIORES),
    OTROS_PANTALONES_DE_CINTURA_ALTA(SubType.OTROS_INFERIORES),
    OTROS_PANTALONES_ACAMPANADOS(SubType.OTROS_INFERIORES),
    OTROS_PANTALONES_DE_LINO(SubType.OTROS_INFERIORES),
    PANTALONES_OTROS_OTROS(SubType.OTROS_INFERIORES),

    /////////////////
    //OUTWEAR
    ABRIGO_LARGO(SubType.ABRIGO),
    ABRIGO_TRENCH(SubType.ABRIGO),
    ABRIGO_DE_LANA(SubType.ABRIGO),
    ABRIGO_PUFFER(SubType.ABRIGO),

    CHAQUETA_DE_CUERO(SubType.CHAQUETA),
    CHAQUETA_DE_MEZCLILLA(SubType.CHAQUETA),
    CHAQUETA_BOMBER(SubType.CHAQUETA),
    CHAQUETA_DE_PUNTO(SubType.CHAQUETA),

    ROMPEVIENTO_ROMPEVIENTO(SubType.ROMPEVIENTO),

    PARKA_FORRADA(SubType.PARKA),
    PARKA_IMPERMEABLE(SubType.PARKA),

    SUDADERA_DE_ALGODÓN(SubType.SUDADERA_CON_CAPUCHA),
    SUDADERA_ESTILO_CALLE(SubType.SUDADERA_CON_CAPUCHA),

    OTROS_PONCHO(SubType.OTROS_ABRIGOS),
    OTROS_CÁRDIGAN(SubType.OTROS_ABRIGOS),
    OTROS_IMPERMEABLE(SubType.OTROS_ABRIGOS),
    ABRIGOS_OTROS(SubType.OTROS_ABRIGOS),

    ////////////////
    //FOOTWEAR
    ZAPATILLAS_ATLETICAS(SubType.ZAPATILLAS),
    ZAPATILLAS_CASUALES(SubType.ZAPATILLAS),
    ZAPATILLAS_DE_ALTA_CANA(SubType.ZAPATILLAS),

    BOTAS_DE_TOBILLO(SubType.BOTAS),
    BOTAS_HASTA_LA_RODILLA(SubType.BOTAS),
    BOTAS_COMBAT(SubType.BOTAS),
    BOTAS_CHELSEA(SubType.BOTAS),

    ZAPATOS_DE_TRAJE_OXFORD(SubType.ZAPATOS_DE_TRAJE),
    ZAPATOS_DE_TRAJE_LOAFERS(SubType.ZAPATOS_DE_TRAJE),
    ZAPATOS_DE_TRAJE_DERBY(SubType.ZAPATOS_DE_TRAJE),
    ZAPATOS_DE_TRAJE_MONK_STRAP(SubType.ZAPATOS_DE_TRAJE),

    SANDALIAS_DE_PLAYA(SubType.SANDALIAS),
    SANDALIAS_SLIDE(SubType.SANDALIAS),
    SANDALIAS_CON_TIRAS(SubType.SANDALIAS),
    SANDALIAS_GLADIADOR(SubType.SANDALIAS),

    TACONES_STILETTO(SubType.TACONES),
    TACONES_BLOQUE(SubType.TACONES),
    TACONES_DE_CUNA(SubType.TACONES),
    TACONES_KITTEN(SubType.TACONES),

    MOCASINES_FLATS(SubType.ZAPATOS_PLANOS),
    ZAPATOS_PLANOS_SLIP_ON(SubType.ZAPATOS_PLANOS),

    ZAPATOS_DE_CASA(SubType.ZAPATOS_DE_CASA),
    MOCASINES(SubType.ZAPATOS_DE_CASA),

    OTROS_BOTAS_DE_LLUVIA(SubType.OTROS_CALZADOS),
    OTROS_BOTAS_DE_MONTAÑA(SubType.OTROS_CALZADOS),
    CALZADO_OTRO_OTRO(SubType.OTROS_CALZADOS),

    /////////////
    //FULL BODY
    VESTIDO_DE_COCTEL(SubType.VESTIDOS),
    VESTIDO_CASUAL(SubType.VESTIDOS),
    VESTIDO_DE_NOCHE(SubType.VESTIDOS),
    VESTIDO_MAXI(SubType.VESTIDOS),
    VESTIDO_MIDI(SubType.VESTIDOS),
    VESTIDO_MINI(SubType.VESTIDOS),
    VESTIDO_CRUZADO(SubType.VESTIDOS),
    VESTIDO_CAMISA(SubType.VESTIDOS),

    OVEROL_DE_MEZCLILLA(SubType.OVEROL),
    OVEROL_CORTO(SubType.OVEROL),
    OVEROL_DE_UTILIDAD(SubType.OVEROL),

    CUERPO_COMPLETO_OTRO_OTRO(SubType.OTROS_CUERPO_COMPLETO),

    ///////////
    //ACCESSORY
    SOMBRERO(SubType.ACCESORIOS_DE_CABEZA),
    GORRA(SubType.ACCESORIOS_DE_CABEZA),
    GORRO(SubType.ACCESORIOS_DE_CABEZA),
    BOINA(SubType.ACCESORIOS_DE_CABEZA),
    SOMBRERO_DE_SOL(SubType.ACCESORIOS_DE_CABEZA),

    BUFANDA_DE_INVIERNO(SubType.BUFANDA),
    BUFANDA_CASUAL(SubType.BUFANDA),

    ACCESORIOS_OTROS_OTROS(SubType.OTROS_ACCESORIOS);

    private final SubType subType;

    ClothingTypeEnum(SubType subType) {
        this.subType = subType;
    }

    public SubType getSubType() {
        return subType;
    }

    //SEGUNDO ENUM
    enum SubType {
        //UPPER
        CAMISETA(Type.SUPERIOR),
        CAMISA(Type.SUPERIOR),
        BLUSA(Type.SUPERIOR),
        SUDADERA(Type.SUPERIOR),
        TOP(Type.SUPERIOR),
        OTROS_SUPERIORES(Type.SUPERIOR),

        //BOTTOM
        PANTALONES(Type.INFERIOR),
        FALDA(Type.INFERIOR),
        LEGGINGS(Type.INFERIOR),
        PANTALONES_CORTOS(Type.INFERIOR),
        BAÑADOR_INFERIOR(Type.INFERIOR),
        OTROS_INFERIORES(Type.INFERIOR),

        //OUTWEAR
        ABRIGO(Type.ABRIGO),
        CHAQUETA(Type.ABRIGO),
        ROMPEVIENTO(Type.ABRIGO),
        PARKA(Type.ABRIGO),
        CAPA(Type.ABRIGO),
        SUDADERA_CON_CAPUCHA(Type.ABRIGO),
        OTROS_ABRIGOS(Type.ABRIGO),

        //FOOTWEAR
        ZAPATILLAS(Type.CALZADO),
        BOTAS(Type.CALZADO),
        ZAPATOS_DE_TRAJE(Type.CALZADO),
        SANDALIAS(Type.CALZADO),
        TACONES(Type.CALZADO),
        ZAPATOS_PLANOS(Type.CALZADO),
        ZAPATOS_DE_CASA(Type.CALZADO),
        OTROS_CALZADOS(Type.CALZADO),

        //FULL BODY
        VESTIDOS(Type.CUERPO_COMPLETO),
        OVEROL(Type.CUERPO_COMPLETO),
        OTROS_CUERPO_COMPLETO(Type.CUERPO_COMPLETO),

        //ACCESSORY
        ACCESORIOS_DE_CABEZA(Type.ACCESORIO),
        ACCESSORIO_FORMAL(Type.ACCESORIO),
        BUFANDA(Type.ACCESORIO),
        GAFAS(Type.ACCESORIO),
        OTROS_ACCESORIOS(Type.ACCESORIO);


        private final Type type;

        SubType(Type type) {
            this.type = type;
        }

        public Type getType() {
            return type;
        }

        enum Type {
            SUPERIOR,
            INFERIOR,
            ABRIGO,
            CALZADO,
            CUERPO_COMPLETO,
            ACCESORIO,
        }

    }

}