package com.example.vcloset.logic.entity.clothing.clothingType;

public enum ClothingTypeEnum {

    T_SHIRT_SHORT_SLEEVE(SubType.UPPER_T_SHIRT),
    T_SHIRT_LONG_SLEEVE(SubType.UPPER_T_SHIRT),
    T_SHIRT_SLEEVELESS(SubType.UPPER_T_SHIRT),

    SHIRT_CASUAL(SubType.UPPER_SHIRT),
    SHIRT_FORMAL(SubType.UPPER_SHIRT),
    SHIRT_BUTTON_DOWN(SubType.UPPER_SHIRT),
    SHIRT_POLO(SubType.UPPER_SHIRT),

    BLOUSE_CASUAL(SubType.UPPER_BLOUSE),
    BLOUSE_ELEGANT(SubType.UPPER_BLOUSE),
    BLOUSE_SHORT_SLEEVE(SubType.UPPER_BLOUSE),
    BLOUSE_LONG_SLEEVE(SubType.UPPER_BLOUSE),

    SWEATSHIRT_WITH_HOOD(SubType.UPPER_SWEATSHIRT),
    SWEATSHIRT_WITHOUT_HOOD(SubType.UPPER_SWEATSHIRT),
    SWEATSHIRT_ZIP_UP(SubType.UPPER_SWEATSHIRT),

    TOP_CROP_TOP(SubType.UPPER_TOP),
    TOP_BRALETTE(SubType.UPPER_TOP),
    TOP_TANK_TOP(SubType.UPPER_TOP),

    UPPER_OTHERS_OTHER(SubType.UPPER_OTHERS),

    ////////////////////
    //PANTS
    PANTS_JEAN(SubType.BOTTOM_PANTS),
    PANTS_DRESS(SubType.BOTTOM_PANTS),
    PANTS_SWEETPANTS(SubType.BOTTOM_PANTS),
    PANTS_CARGO(SubType.BOTTOM_PANTS),

    SKIRT_PENCIL(SubType.BOTTOM_SKIRT),
    SKIRT_LONG(SubType.BOTTOM_SKIRT),
    SKIRT_MIDI(SubType.BOTTOM_SKIRT),
    SKIRT_MINI(SubType.BOTTOM_SKIRT),
    SKIRT_PLEATED(SubType.BOTTOM_SKIRT),

    LEGGINGS_ATHLETIC(SubType.BOTTOM_LEGGINGS),
    LEGGINGS_CASUAL(SubType.BOTTOM_LEGGINGS),
    LEGGINGS_FAUX_LEATHER(SubType.BOTTOM_LEGGINGS),

    SHORTS_CASUAL(SubType.BOTTOM_SHORTS),
    SHORTS_ATHLETIC(SubType.BOTTOM_SHORTS),
    SHORTS_DENIM(SubType.BOTTOM_SHORTS),
    SHORTS_BERMUDA(SubType.BOTTOM_SHORTS),

    SWIMWEAR_ATHLETIC_SWIM_SHORTS(SubType.BOTTOM_SWIMWEAR),
    SWIMWEAR_CASUAL_SWIM_SHORTS(SubType.BOTTOM_SWIMWEAR),

    OTHERS_CULOTTES(SubType.BOTTOM_OTHERS),
    OTHERS_HIGH_WAISTED_PANTS(SubType.BOTTOM_OTHERS),
    OTHERS_FLARED_PANTS(SubType.BOTTOM_OTHERS),
    OTHERS_LINEN_PANTS(SubType.BOTTOM_OTHERS),
    PANTS_OTHERS_OTHER(SubType.BOTTOM_OTHERS),

    /////////////////
    //OUTWEAR
    COAT_LONG(SubType.OUTWEAR_COAT),
    COAT_TRENCH(SubType.OUTWEAR_COAT),
    COAT_WOOL(SubType.OUTWEAR_COAT),
    COAT_PUFFER(SubType.OUTWEAR_COAT),

    JACKET_LEATHER(SubType.OUTWEAR_JACKET),
    JACKET_DENIM(SubType.OUTWEAR_JACKET),
    JACKET_BOMBER(SubType.OUTWEAR_JACKET),
    JACKET_KNIT(SubType.OUTWEAR_JACKET),

    WINDBREAKER_WINDBREAKER(SubType.OUTWEAR_WINDBREAKER),

    PARKA_LINED(SubType.OUTWEAR_PARKA),
    PARKA_WATERPROOF(SubType.OUTWEAR_PARKA),

    HOODIE_COTTON(SubType.OUTWEAR_HOODIE),
    HOODIE_STREET_STYLE(SubType.OUTWEAR_HOODIE),

    OTHERS_PONCHO(SubType.OUTWEAR_OTHERS),
    OTHERS_CARDIGAN(SubType.OUTWEAR_OTHERS),
    OTHERS_RAINCOAT(SubType.OUTWEAR_OTHERS),
    OUTWEAR_OTHERS_OTHER(SubType.OUTWEAR_OTHERS),

    ////////////////
    //FOOTWEAR
    SNEAKERS_ATHLETIC(SubType.FOOTWEAR_SNEAKERS),
    SNEAKERS_CASUAL(SubType.FOOTWEAR_SNEAKERS),
    SNEAKERS_HIGH_TOP(SubType.FOOTWEAR_SNEAKERS),

    BOOTS_ANKLE(SubType.FOOTWEAR_BOOTS),
    BOOTS_KNEE_HIGH(SubType.FOOTWEAR_BOOTS),
    BOOTS_COMBAT(SubType.FOOTWEAR_BOOTS),
    BOOTS_CHELSEA(SubType.FOOTWEAR_BOOTS),

    DRESS_SHOES_OXFORDS(SubType.FOOTWEAR_DRESS_SHOES),
    DRESS_SHOES_LOAFERS(SubType.FOOTWEAR_DRESS_SHOES),
    DRESS_SHOES_DERBY(SubType.FOOTWEAR_DRESS_SHOES),
    DRESS_SHOES_MONK_STRAP_SHOES(SubType.FOOTWEAR_DRESS_SHOES),

    SANDALS_FLIP_FLOPS(SubType.FOOTWEAR_SANDALS),
    SANDALS_SLIDE(SubType.FOOTWEAR_SANDALS),
    SANDALS_STRAPPY(SubType.FOOTWEAR_SANDALS),
    SANDALS_GLADIATOR(SubType.FOOTWEAR_SANDALS),

    HEELS_STILETTO(SubType.FOOTWEAR_HEELS),
    HEELS_BLOCK(SubType.FOOTWEAR_HEELS),
    HEELS_WEDGE(SubType.FOOTWEAR_HEELS),
    HEELS_KITTEN(SubType.FOOTWEAR_HEELS),

    FLATS_LOAFERS(SubType.FOOTWEAR_FLATS),
    FLATS_SLIP_ON_FLATS(SubType.FOOTWEAR_FLATS),

    SLIPPERS_HOUSE_SLIPPERS(SubType.FOOTWEAR_SLIPPERS),
    SLIPPERS_MOCCASINS(SubType.FOOTWEAR_SLIPPERS),

    OTHERS_RAIN_BOOTS(SubType.FOOTWEAR_OTHERS),
    OTHERS_HIKING_BOOTS(SubType.FOOTWEAR_OTHERS),
    FOOTWEAR_OTHERS_OTHER(SubType.FOOTWEAR_OTHERS),

    /////////////
    //FULL BODY
    DRESS_COCKTAIL_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_CASUAL_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_EVENING_GOWN(SubType.FULL_BODY_DRESSES),
    DRESS_MAXI_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_MIDI_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_MINI_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_WRAP_DRESS(SubType.FULL_BODY_DRESSES),
    DRESS_SHIRT_DRESS(SubType.FULL_BODY_DRESSES),

    OVERALL_DENIM_OVERALL(SubType.FULL_BODY_OVERALLS),
    OVERALL_SHORT_OVERALL(SubType.FULL_BODY_OVERALLS),
    OVERALL_UTILITY_OVERALL(SubType.FULL_BODY_OVERALLS),

    FULL_BODY_OTHERS_OTHER(SubType.FULL_BODY_OTHERS),

    ///////////
    //ACCESSORY
    HEAD_WEAR_HAT(SubType.ACCESSORY_HEAD_WEAR),
    HEAD_WEAR_CAP(SubType.ACCESSORY_HEAD_WEAR),
    HEAD_WEAR_BEANIE(SubType.ACCESSORY_HEAD_WEAR),
    HEAD_WEAR_BERET(SubType.ACCESSORY_HEAD_WEAR),
    HEAD_WEAR_SUN_HAT(SubType.ACCESSORY_HEAD_WEAR),

    SCARVES_WINTER_SCARF(SubType.ACCESSORY_SCARVES),
    SCARVES_CASUAL_SCARF(SubType.ACCESSORY_SCARVES),

    ACCESSORY_OTHERS_OTHER(SubType.ACCESSORY_OTHERS);

    private final SubType subType;

    ClothingTypeEnum(SubType subType) {
        this.subType = subType;
    }

    public SubType getSubType() {
        return subType;
    }

    //SEGUNDO ENUM
    enum SubType {
        //UPPER
        UPPER_T_SHIRT(Type.UPPER),
        UPPER_SHIRT(Type.UPPER),
        UPPER_BLOUSE(Type.UPPER),
        UPPER_SWEATSHIRT(Type.UPPER),
        UPPER_TOP(Type.UPPER),
        UPPER_OTHERS(Type.UPPER),

        //BOTTOM
        BOTTOM_PANTS(Type.BOTTOM),
        BOTTOM_SKIRT(Type.BOTTOM),
        BOTTOM_LEGGINGS(Type.BOTTOM),
        BOTTOM_SHORTS(Type.BOTTOM),
        BOTTOM_SWIMWEAR(Type.BOTTOM),
        BOTTOM_OTHERS(Type.BOTTOM),

        //OUTWEAR
        OUTWEAR_COAT(Type.OUTWEAR),
        OUTWEAR_JACKET(Type.OUTWEAR),
        OUTWEAR_WINDBREAKER(Type.OUTWEAR),
        OUTWEAR_PARKA(Type.OUTWEAR),
        OUTWEAR_CAPE(Type.OUTWEAR),
        OUTWEAR_HOODIE(Type.OUTWEAR),
        OUTWEAR_OTHERS(Type.OUTWEAR),

        //FOOTWEAR
        FOOTWEAR_SNEAKERS(Type.FOOTWEAR),
        FOOTWEAR_BOOTS(Type.FOOTWEAR),
        FOOTWEAR_DRESS_SHOES(Type.FOOTWEAR),
        FOOTWEAR_SANDALS(Type.FOOTWEAR),
        FOOTWEAR_HEELS(Type.FOOTWEAR),
        FOOTWEAR_FLATS(Type.FOOTWEAR),
        FOOTWEAR_SLIPPERS(Type.FOOTWEAR),
        FOOTWEAR_OTHERS(Type.FOOTWEAR),

        //FULL BODY
        FULL_BODY_DRESSES(Type.FULL_BODY),
        FULL_BODY_OVERALLS(Type.FULL_BODY),
        FULL_BODY_OTHERS(Type.FULL_BODY),

        //ACCESSORY
        ACCESSORY_HEAD_WEAR(Type.ACCESSORY),
        ACCESSORY_FORMAL(Type.ACCESSORY),
        ACCESSORY_SCARVES(Type.ACCESSORY),
        ACCESSORY_EYEWEAR(Type.ACCESSORY),
        ACCESSORY_OTHERS(Type.ACCESSORY);


        private final Type type;

        SubType(Type type) {
            this.type = type;
        }

        public Type getType() {
            return type;
        }

        enum Type {
            UPPER,
            BOTTOM,
            OUTWEAR,
            FOOTWEAR,
            FULL_BODY,
            ACCESSORY,
        }

    }

}