name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from 'qa'
        if: github.base_ref != 'qa'
        run: |
          echo "PR must originate from the 'qa' branch."
          exit 1
